EventPlanner/Models/AddEventToGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventPlanner.Models
{
    public class AddEventToGroupViewModel
    {
        public Group Group { get; set; }
        public SelectList Events { get; set; }
        public Event Event { get; set; }
    }
}

EventPlanner/Models/AttendeeViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventPlanner.Models
{
    public class GroupCreateViewModel
    {
        [Required]
        [Display(Name = "User Name")]
        public string CurrentUserId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Group Name")]
        public Group Group{ get; set; }

        [Required]
        [Display(Name = "Event")]
        public Event Event { get; set; }

        [Display(Name = "Events")]
        public SelectList Events { get; set; }
    }

    public class GroupEditViewModel
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Group Name")]
        public string Name { get; set; }
    }
}

EventPlanner/Models/DeleteGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventPlanner.Models
{
    public class DeleteGroupViewModel
    {
        public Group Group { get; set; }
        public List<Group> GroupsToDelete { get; set; }
        public List<GroupToEvents> GroupToEventsToDelete { get; set; }
        public List<UserToGroup> UserToGroupsToDelete { get; set; }
    }
}

EventPlanner/Models/VoteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventPlanner.Models
{
    public class VoteViewModel
    {
        public List<Entertainment> entertainments { get; set; }
        public Group group { get; set; }
        public bool pointsAccepted { get; set; }
        public Entertainment name { get; set; }

    }
}

EventPlanner/Controllers/AttendeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventPlanner.Models;
using Microsoft.AspNet.Identity;

namespace EventPlanner.Controllers
{
    public class AttendeeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Attendee
        [Authorize]
        public ActionResult Index()
        {
            var AttendeeGroupModel = new AttendeeGroupViewModel();
            var currentUserId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var acceptedGroups = (from x in db.UserToGroups where x.UserId == currentUserId && x.AcceptedInvite == true select x.Group).ToList();
            var invitedGroups = (from x in db.UserToGroups where x.UserId == currentUserId && x.AcceptedInvite == false select x.Group).ToList();
            AttendeeGroupModel.CurrentGroups = acceptedGroups;
            AttendeeGroupModel.Invites = invitedGroups;
            AttendeeGroupModel.User = db.Users.Find(currentUserId);
            foreach(ApplicationUser user in db.Users)
            {
                if (user.Id == currentUserId)
                {
                    AttendeeGroupModel.User = user;
                }
            }
            return View(AttendeeGroupModel);
        }

        public ActionResult LeaveGroup (string userId, int? groupId)
        {

            UserToGroup userToGroupToRemove = (from row in db.UserToGroups where row.UserId == userId && row.GroupId == groupId select row).First();
            db.UserToGroups.Remove(userToGroupToRemove);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AcceptGroupInvite (int? id)
        {
            int userToGroupToAccept = (from x in db.UserToGroups where x.GroupId == id && x.AcceptedInvite == false select x.Id).First();
            db.UserToGroups.Find(userToGroupToAccept).AcceptedInvite = true;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult DeclineGroupInvite (int? id)
        {
            var userToGroupToDecline = (from x in db.UserToGroups where x.GroupId == id && x.AcceptedInvite == false select x).First();
            db.UserToGroups.Remove(userToGroupToDecline);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        
        public ActionResult RemoveMemberFromGroup(string userId, int groupId)
        {
            var idSearched = (from row in db.UserToGroups where row.UserId == userId && row.GroupId == groupId select row.Id);
            int idToSearch = idSearched.First();
            var UserToGroupToRemove = db.UserToGroups.Find(idToSearch);
            db.UserToGroups.Remove(UserToGroupToRemove);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = groupId });

        }

        //GET
        public ActionResult AddEventToGroup(int? groupId)
        {
            AddEventToGroupViewModel addEventToGroupModel = new AddEventToGroupViewModel();
            addEventToGroupModel.Events = new SelectList(db.Events, "Id", "Name");
            addEventToGroupModel.Group = db.Groups.Find(groupId);
            return View(addEventToGroupModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddEventToGroup(AddEventToGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                GroupToEvents groupToEventToAdd = new GroupToEvents { GroupId = model.Group.Id, EventId = model.Event.Id };
                db.GroupToEvents.Add(groupToEventToAdd);
                db.SaveChanges();                
            }
            return RedirectToAction("Details", new { id = model.Group.Id });
        }

        public ActionResult RemoveEventFromGroup(int eventId, int groupId)
        {
            var idsearched = (from row in db.GroupToEvents where row.EventId == eventId && row.GroupId == groupId select row.Id);
            int idToSearch = idsearched.First();
            var GroupToEventsToRemove = db.GroupToEvents.Find(idToSearch);
            db.GroupToEvents.Remove(GroupToEventsToRemove);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = groupId });

        }

        // GET: Attendee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupToEventsViewModel GroupToEvents = new GroupToEventsViewModel();
            Group Group = db.Groups.Find(id);            
            var users = (from row in db.UserToGroups where row.GroupId == id select row.User).ToList();
            var events = (from row in db.GroupToEvents where row.GroupId == id select row.Event).ToList();
            GroupToEvents.Group = Group;
            GroupToEvents.CurrentUsers = users;
            GroupToEvents.Events = events;

            return View(GroupToEvents);
        }

        // GET: Attendee/Create
        public ActionResult Create()
        {
            GroupCreateViewModel groupCreateModel = new GroupCreateViewModel();
            groupCreateModel.CurrentUserId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            groupCreateModel.Events = new SelectList(db.Events, "Id", "Name");

            return View(groupCreateModel);
        }

        // POST: Attendee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GroupCreateViewModel model)
        //public ActionResult Create([Bind(Include = "Id,UserId,GroupId")] UserToGroup userToGroup)
        {
            if (ModelState.IsValid)
            {
                var newGroup = new Group{ Name = model.Group.Name };
                var newUserToGroup = new UserToGroup { UserId = model.CurrentUserId, GroupId = newGroup.Id, AcceptedInvite = true };
                var newGroupToEvent = new GroupToEvents { GroupId = newGroup.Id, EventId = model.Event.Id };
                db.Groups.Add(newGroup);
                db.UserToGroups.Add(newUserToGroup);
                db.GroupToEvents.Add(newGroupToEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Name");
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name");
            return View();
        }

        // GET: Attendee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var GroupToAttendees = new GroupToAttendeesViewModel();
                foreach(Group group in db.Groups)
                {
                    if(group.Id == id)
                    {
                        GroupToAttendees.Group = group;
                    }
                }
                var currentUsers = (from row in db.UserToGroups where row.GroupId == id select row.User).ToList();
                GroupToAttendees.CurrentUsers = currentUsers;
                return View(GroupToAttendees);
            }            
        }

        // POST: Attendee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GroupEditViewModel model, UserToGroup userToGroup, int? id)
        {
            if (ModelState.IsValid)
            {
                var groupToUpdate = db.Groups.Find(db.UserToGroups.Find(userToGroup.Id).GroupId);
                var userToGroupToUpdate = db.UserToGroups.Find(userToGroup.Id);
                userToGroupToUpdate.GroupId = groupToUpdate.Id;
                groupToUpdate.Name = model.Name;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Name", userToGroup.GroupId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", userToGroup.UserId);
            return View(userToGroup);
        }

        // GET: Attendee/Delete/5
        [HttpGet]
        public ActionResult DeleteGroup(int id)
        {
            DeleteGroupViewModel DeleteGroupModel = new DeleteGroupViewModel();
            DeleteGroupModel.Group = db.Groups.Find(id);     
            return View(DeleteGroupModel);
        }

        // POST: Attendee/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteGroup(DeleteGroupViewModel DeleteGroupModel)
        {
            foreach (GroupToEvents groupToEvent in db.GroupToEvents)
            {
                if (DeleteGroupModel.Group.Id == groupToEvent.GroupId)
                {
                    db.GroupToEvents.Remove(groupToEvent);
                }
            }
            foreach (Group group in db.Groups)
            {
                if (DeleteGroupModel.Group.Id == group.Id)
                {
                    db.Groups.Remove(group);
                    break;
                }
            }
            foreach (UserToGroup userToGroup in db.UserToGroups)
            {

EventPlanner/Views/Attendee/AddEventToGroup.cshtml
@model EventPlanner.Models.AddEventToGroupViewModel
@{
    ViewBag.Title = "AddEventToGroup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Event To @Model.Group.Name</h2>

<h2>Please select an event.</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserToGroup</h4>
        <hr />
        @Html.HiddenFor(m => m.Group.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Events, "Events", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Event.Id, Model.Events, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Event, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Event" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Groups", "Details")
</div>

EventPlanner/Views/Attendee/Create.cshtml
@model EventPlanner.Models.GroupCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a Group</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color:#ffffff">
        <hr />
        @Html.HiddenFor(m => m.CurrentUserId)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Group, "Group Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Group.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Group, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Event, "Events", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Event.Id, Model.Events, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Event, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EventPlanner/Views/Attendee/CreateOG.cshtml
@model EventPlanner.Models.UserToGroup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserToGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, "Group Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Group Name", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.DropDownList("GroupId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EventPlanner/Views/Attendee/DeleteGroup.cshtml
@model EventPlanner.Models.DeleteGroupViewModel

@{
    ViewBag.Title = "Delete";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<h2>Deleting @Model.Group.Name</h2>

<h1 style="color:#ffffff;" >Are you sure you want to delete this group?</h1>
<div style="color:#ffffff">
    <hr />
            @Html.HiddenFor(m => m.Group.Id)
            @*Check Joe's Trash Collector / Add Pickup Hidden Form. @Html.HiddenFor Look Into / How to put information in it*@
            <input type="submit" name="Delete" value="Submit" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")

</div>
}

EventPlanner/Views/Attendee/Details.cshtml
@model EventPlanner.Models.GroupToEventsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Group.Name</h2>

<div style="color:#ffffff">
    <table class="table">
        <thead>
            <tr>
                <th>User Name</th>
                <th>Email</th>
            </tr>
        </thead>              
@foreach (var user in Model.CurrentUsers)
{

    <tr>
        <td>
            @user.UserName
        </td>
        <td>
            @user.Email
        </td>
        <td>
            @Html.ActionLink("Remove", "RemoveMemberFromGroup", new { userId = user.Id, groupId = Model.Group.Id })
        </td>
    </tr>
}
    </table>

    <table class="table">
        @Html.ActionLink("Add Event", "AddEventToGroup", new { groupId = Model.Group.Id })
        <thead>
            <tr>
                <th>Event Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Price</th>
                <th>Web Link</th>
            </tr>
        </thead>
        @foreach (var eve in Model.Events)
        {

            <tr>
                <td>
                    @eve.Name
                </td>
                <td>
                    @eve.StartDate
                </td>
                <td>
                    @eve.EndDate
                </td>
                <td>
                    @eve.Cost
                </td>
                <td>
                    @eve.Weblink
                </td>
                <td>@Html.ActionLink("Remove", "RemoveEventFromGroup", new { eventId = eve.Id, groupId = Model.Group.Id })</td>
                <td>
                    <form action=~/Attendee/Index method="POST">
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh"
                            data-amount= @eve.Cost
                            data-name="Stripe.com"
                            data-description="Widget"
                            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                            data-locale="auto"
                            data-zip-code="true">
                    </script>
                    </form>
                </td>
            </tr>
        }
    </table>
    @Html.ActionLink("Back", "Index")
</div>

EventPlanner/Views/Attendee/Edit.cshtml
@model EventPlanner.Models.GroupEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit a Group</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserToGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Group Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @*@Html.DropDownList("GroupId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EventPlanner/Views/Attendee/Index.cshtml
@model EventPlanner.Models.AttendeeGroupViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Hello, @Model.User.UserName!</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div  style="color:#ffffff;">
<table class="table">
    <tr>
        <th scope="col">Invites </th>
    </tr>

@foreach (var invite in Model.Invites)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => invite.Name)
        </td>
        <td>
            @Html.ActionLink("Accept", "AcceptGroupInvite", new { id = invite.Id }) |
            @Html.ActionLink("Decline", "DeclineGroupInvite", new { id = invite.Id }) |
        </td>
    </tr>
}

</table>

<table class="table">
    <tr>
        <th scope="col">Group Name </th>
    </tr>

@foreach (var group in Model.CurrentGroups)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => group.Name)
        </td>
        <td>
            @Html.ActionLink("Invite Members", "InviteToGroup", new { id = group.Id })            |
            @Html.ActionLink("Vote For Shows", "Vote", new { GroupId = group.Id })            |
            @Html.ActionLink("View Schedule", "Schedule", new { GroupId = group.Id })            |
            @Html.ActionLink("Group Details", "Details", new { id = group.Id })            |
            @Html.ActionLink("Leave Group", "LeaveGroup", new { userId = Model.User.Id, groupId = group.Id })            |
            @Html.ActionLink("Delete Group", "DeleteGroup", new { id = group.Id })

        </td>
    </tr>
}

</table>
 </div>

EventPlanner/Views/Attendee/InviteToGroup.cshtml
@model EventPlanner.Models.UserToGroup
@{
    ViewBag.Title = "InviteToGroup";
}

<h2>Invite Someone To Your Group!</h2>

<h3 style="color:#ffffff">Please Input the email address of any registered user you would like to invite to the group.</h3>
<br/>
<div style="color:#ffffff">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Entertainment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.User.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.User.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Group.Id)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    </div>


EventPlanner/Views/Attendee/Schedule.cshtml
@model EventPlanner.Models.VoteViewModel
@{
    ViewBag.Title = "Schedule";
}

<h2>Schedule</h2>
<table class="table" style="color:#ffffff;">
    <tr>
        <th>Entertainment Name</th>
        <th>Points</th>
    </tr>
    @foreach (var entertainment in Model.entertainments)
    {
        <tr>
            <td>
                <div>
                    <p> @entertainment.Name</p>
                </div>
            </td>
            <td>
                <div>
                    <p>@entertainment.VenueId</p>
                </div>
            </td>
        </tr>
    }
</table>

<p id="reply">
    <button>Get Forecast</button>

</p>

<script>
    $(document).ready(function () {
        $("button").click(function () {
            $.get("http://api.openweathermap.org/data/2.5/weather?q=Milwaukee&APPID=cea53ed56c3ee5fc14e6d1120b4e9e9d", function (response) {
                //response
                $("#reply").text(response.main.temp));
            });
        });
    });
</script>

EventPlanner/Views/Attendee/Vote.cshtml
@model EventPlanner.Models.VoteViewModel
@{
    ViewBag.Title = "Vote";
}
<h2>Allocate you preference points here. <br /> You have 10 points to allocate to all of the shows at this event.</h2>


@using (Html.BeginForm("Vote", "Attendee", FormMethod.Post))

{
    <table class="table" style="color:#ffffff;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name.Venue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name.EndTime)
            </th>
            <th>
                <label> 18+ Only</label>
            </th>
            <th>
                <label>People With <br /> Disabilities Friendly</label>
            </th>
            <th>
                <label>Outdoor Location </label>
            </th>
            <th>
                <label> Points </label>
            </th>
            <th></th>
        </tr>

        @Html.AntiForgeryToken()

        @for (int i = 0; i < Model.entertainments.Count; i++)
        {
            @Html.HiddenFor(model => Model.entertainments[i].Id)
            <tr>
                <td>
                    @Html.DisplayFor(m => m.entertainments[i].Name)
                </td>
                <td>
                    @Html.DisplayFor(m => m.entertainments[i].Venue.Name)
                </td>
                <td>
                    @Html.DisplayFor(m => m.entertainments[i].StartTime.Hour)
                </td>
                <td>
                    @Html.DisplayFor(m => m.entertainments[i].EndTime.Hour)
                </td>
                <td>
                    @if (Model.entertainments[i].IsAgeEighteenPlus == false)
                    {
                        <p> Yes</p>
                    }
                    else
                    {
                        <p> No </p>
                    }
                    @Html.HiddenFor(m => m.entertainments[i].IsAgeEighteenPlus)
                </td>
                <td>
                    @if (Model.entertainments[i].IsDisabledFriendly == true)
                    {
                        <p>Yes </p>
                    }
                    else
                    {
                        <p> No </p>
                    }
                    @Html.HiddenFor(m => m.entertainments[i].IsDisabledFriendly)
                </td>
                <td>
                    @if (Model.entertainments[i].IsOutdoors == true)
                    {
                        <p> Yes</p>
                    }
                    else
                    {
                        <p> No </p>
                    }
                    @Html.HiddenFor(m => m.entertainments[i].IsOutdoors)
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => Model.entertainments[i].VenueId)
                        </div>
                    </div>
                </td>
            </tr>
        }
    </table>

    <div class="form-group">
        @Html.HiddenFor(model => model.group.Id)
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

        }