EventPlanner/Models/CreateEntertainmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventPlanner.Models
{
    public class CreateEntertainmentViewModel
    {
        public Entertainment CurrentEntertainment { get; set; }
        public ApplicationUser Promoter { get; set; }
        public Event CurrentEvent { get; set; }
        public SelectList PreMadeVenues { get; set; }
        public int CurrentVenueId { get; set; }
        public int CurrentEventId { get; set; }

    }
}

EventPlanner/Models/CreateVenueViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventPlanner.Models
{
    public class CreateVenueViewModel
    {
        public Venue CurrentVenue { get; set; }
        public int IdOfEvent { get; set; }
    }
}

EventPlanner/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EventPlanner.Models
{
    public class Event
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Event")]
        public string Name { get; set; }
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }
        [Display(Name = "Start Time")]
        public DateTime StartTime { get; set; }
        [Display(Name = "End Time")]
        public DateTime EndTime { get; set; }
        public int Cost { get; set; }
        [Display(Name = "Link")]
        public string Weblink { get; set; }
        [Display(Name = "Number")]
        public string AddressNumber { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }
        public string PromoterId { get; set; }
        [ForeignKey("PromoterId")]
        public ApplicationUser User { get; set; }
    }
}

EventPlanner/Models/ViewVenuesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventPlanner.Models
{
    public class ViewVenuesViewModel
    {
        public List <Venue> UserVenues { get; set; }
        public List<Entertainment> UserEntertainment { get; set; }
    }
}

EventPlanner/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventPlanner.Models;
using Microsoft.AspNet.Identity;

namespace EventPlanner.Controllers
{
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db.Events.ToList().Where(n => n.PromoterId == User.Identity.GetUserId()));
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            var eventDetailsModel = new EventDetialsViewModel();
            eventDetailsModel.CurrentEvent= db.Events.Find(id);
            eventDetailsModel.EventVenues = new List<Venue>();
            foreach (Venue thisEventVenue in db.Venues)
            {
                if (thisEventVenue.EventId == eventDetailsModel.CurrentEvent.Id)
                {
                    eventDetailsModel.EventVenues.Add(thisEventVenue);
                }
            }
            return View(eventDetailsModel);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,StartDate,EndDate,StartTime,EndTime,Cost,Weblink,AddressNumber,Street,City,State,ZipCode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                @event.PromoterId = User.Identity.GetUserId();
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,StartDate,EndDate,StartTime,EndTime,Cost,Weblink,AddressNumber,Street,City,State,ZipCode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventPlanner/Controllers/PromoterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventPlanner.Models;
using Microsoft.AspNet.Identity;

namespace EventPlanner.Controllers
{
    public class PromoterController : Controller
    {
        ApplicationDbContext db;
        public PromoterController()
        {
            db = new ApplicationDbContext();
        }

        // GET: Promoter
        public ActionResult Index()
        {
            var entertainments = db.Entertainments.Include(e => e.Event).Include(e => e.Venue);
            return View(entertainments.ToList());
        }

        // GET: Promoter/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entertainment entertainment = db.Entertainments.Find(id);
            if (entertainment == null)
            {
                return HttpNotFound();
            }
            return View(entertainment);
        }

        [HttpGet]
        public ActionResult CreateEntertainment(int id)
        {
            var EntertainmentModel = new CreateEntertainmentViewModel
            {
                PreMadeVenues = new SelectList(db.Venues, "Id", "Name")
            };
            var currentUserId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            foreach (ApplicationUser user in db.Users)
            {
                if (user.Id == currentUserId)
                {
                    EntertainmentModel.Promoter = user;
                }
            }
            foreach (Event foundEvent in db.Events)
            {
                if (foundEvent.Id == id)
                {
                    EntertainmentModel.CurrentEvent = foundEvent;
                    EntertainmentModel.CurrentEventId = foundEvent.Id;
                }
            }
            return View(EntertainmentModel);

        }
        [HttpPost]
        public ActionResult CreateEntertainment(CreateEntertainmentViewModel createEntertainmentViewModel)
        {
            var newEntertainment = new Entertainment
            {
                Name = createEntertainmentViewModel.CurrentEntertainment.Name,
                StartTime = createEntertainmentViewModel.CurrentEntertainment.StartTime,
                EndTime = createEntertainmentViewModel.CurrentEntertainment.EndTime,
                StartDate = createEntertainmentViewModel.CurrentEntertainment.StartDate,
                EndDate = createEntertainmentViewModel.CurrentEntertainment.EndDate,
                Restriction = createEntertainmentViewModel.CurrentEntertainment.Restriction,
                VenueId = createEntertainmentViewModel.CurrentVenueId,
                EventId = createEntertainmentViewModel.CurrentEventId,
            };
            db.Entertainments.Add(newEntertainment);
            db.SaveChanges();
            return RedirectToAction("Index", "Events");

        }
        [HttpGet]
        public ActionResult CreateVenue(int id)
        {
            var newCreateVenueModel = new CreateVenueViewModel
            {
                IdOfEvent = id
            };
            return View(newCreateVenueModel);
        }
        [HttpPost]
        public ActionResult CreateVenue(CreateVenueViewModel model)
        {
            var newVenue = new Venue
            {
                Name = model.CurrentVenue.Name,
                Latitude = model.CurrentVenue.Latitude,
                Longitude = model.CurrentVenue.Longitude,
                IsDisabledFriendly = model.CurrentVenue.IsDisabledFriendly,
                IsOutdoors = model.CurrentVenue.IsOutdoors,
                HasSeating = model.CurrentVenue.HasSeating,
            };
            foreach (Event foundEvent in db.Events)
            {
                if (foundEvent.Id == model.IdOfEvent)
                {
                    newVenue.Event = foundEvent;
                }
            }
            int eventId = model.IdOfEvent;
            db.Venues.Add(newVenue);
            db.SaveChanges();
            return RedirectToAction("Index", "Events", new { id = eventId });

        }
        // GET: Promoter/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entertainment entertainment = db.Entertainments.Find(id);
            if (entertainment == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name", entertainment.EventId);
            ViewBag.VenueId = new SelectList(db.Venues, "Id", "Name", entertainment.VenueId);
            return View(entertainment);
        }

        // POST: Promoter/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,StartTime,EndTime,StartDate,EndDate,Restriction,VenueId,EventId")] Entertainment entertainment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entertainment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name", entertainment.EventId);
            ViewBag.VenueId = new SelectList(db.Venues, "Id", "Name", entertainment.VenueId);
            return View(entertainment);
        }

        // GET: Promoter/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entertainment entertainment = db.Entertainments.Find(id);
            if (entertainment == null)
            {
                return HttpNotFound();
            }
            return View(entertainment);
        }

        // POST: Promoter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entertainment entertainment = db.Entertainments.Find(id);
            db.Entertainments.Remove(entertainment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // GET: Promoter/Events
        public ActionResult Events()
        {
            var events = db.Events;
            return View(events.ToList());
        }
        // GET: Promoter/MyInfo
        public ActionResult MyInfo()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Where(n => n.Id == userId);
            return View(user.ToList());
        }
        // GET: Promoter/CreateEvent
        public ActionResult CreateEvent()
        {
            ViewBag.AddressId = new SelectList(db.Addresses, "Id", "Name");
            return View();
        }

        // POST: Promoter/CreateEvent
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEvent([Bind(Include = "Name,StartTime,EndTime,StartDate,EndDate,Weblink,AddressId")] Event newEvent)
        {
            //Address address = new Address();
            //newEvent.AddressId = address.Id;
            if (ModelState.IsValid)
            {
                db.Events.Add(newEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(newEvent);
        }

        public ActionResult ViewVenues(int Id)
        {
            var viewVenuesViewModel = new ViewVenuesViewModel();
            viewVenuesViewModel.UserVenues = new List<Venue>();
            viewVenuesViewModel.UserEntertainment = new List<Entertainment>();
            //try
            //{
            foreach (Venue venue in db.Venues)
            {
                if (Id == venue.EventId)
                {
                    viewVenuesViewModel.UserVenues.Add(venue);
                }
            }
            foreach (Entertainment entertainment in db.Entertainments)
            {
                if(Id == entertainment.EventId)
                {
                    viewVenuesViewModel.UserEntertainment.Add(entertainment);
                }
            }
            return View(viewVenuesViewModel);
        }
    }
}

EventPlanner/Views/Promoter/Create.cshtml
@model EventPlanner.Models.Entertainment

@{
    ViewBag.Title = "Create";
}
@Html.ActionLink("CreateVenue", "CreateVenue", "Promoter", new { id = Model.Id}, new { target = "_blank" })
<h2>Create</h2>

@using (Html.BeginForm())
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>Entertainment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
            

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restriction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Restriction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restriction, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.VenueId, "Venue", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("Venue", (SelectList)(ViewBag.VenueId), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


EventPlanner/Views/Promoter/CreateVenue.cshtml
@model EventPlanner.Models.CreateVenueViewModel
@{
    ViewBag.Title = "CreateVenue";
}

@using (Html.BeginForm("CreateVenue", "Promoter", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color:#ffffff;">
        <h4> Create Venue</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="row">
                <div class="col-md-10">
                    <label> Venue Name </label>
                </div>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.CurrentVenue.Name, new { @class = "form=control" })
                    @Html.ValidationMessageFor(m => m.CurrentVenue.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-10">
                    <label> Restrictions</label>
                </div>
                <div class="col-md-10">
                    <div class=" row">
                        @Html.CheckBoxFor(m => m.CurrentVenue.IsOutdoors, "False")
                        <label> Outdoors</label>
                    </div>
                    <div class=" row">
                        @Html.CheckBoxFor(m => m.CurrentVenue.IsDisabledFriendly, "False")
                        <label> People with Disabilities Friendly </label>
                    </div>
                    <div class=" row">
                        @Html.CheckBoxFor(m => m.CurrentVenue.HasSeating, "False")
                        <label> 18+ Only </label>
                    </div>
                </div>
            </div>
            @Html.HiddenFor(m => m.IdOfEvent)
            @Html.HiddenFor(m => m.CurrentVenue.Latitude, new { @id = "latitude"})
            @Html.HiddenFor(m => m.CurrentVenue.Longitude, new { @id = "longitude"})
            <div class="form-group">
                <div class="col-md-offset-2 col-md-5">
                    <input type="submit" value="Create Venue" class="btn btn-default" label="CreateVenue" />
                </div>
            </div>
        </div>
    </div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*<%@ Page Language="C#" AutoEventWireup="true" CodeFile="sample.aspx.cs" Inherits="sample" %>*@

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Show Google Map with Latitude and Longitude in asp.net website</title>
    <style type="text/css">
        html {
            height: 100%;
        }

        body {
            height: 100%;
            margin: 0;
            padding: 0;
            vertical-align: top
        }

        #map_canvas {
            height: 100%;
        }
    </style>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6v5-2uaq_wusHDktM9ILcqIrlPtnZgEk&sensor=false">
    </script>
    <script type="text/javascript">

        function initialize() {
            var myLatlng = new google.maps.LatLng(43.038902, -87.906471);
            var myOptions = {
                zoom: 7,
                center: myLatlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            map = new google.maps.Map(document.getElementById("gmap"), myOptions);
            var marker
                = new google.maps.Marker({
                    map: map
                });
            google.maps.event.addListener(marker, 'dblclick', function () {
                zoomLevel = map.getZoom() + 1;
                if (zoomLevel == 20) {
                    zoomLevel = 10;
                }
                document.getElementById("zoom_level").innerHTML = zoomLevel;
                map.setZoom(zoomLevel);
            });
            function placeMarker(location) {
                if (marker) {
                    marker.setPosition(location);
                } else {
                    marker = new google.maps.Marker({
                        position: location,
                        map: map
                    });
                }
            }
            google.maps.event.addListener(map, 'click', function (event) {
                placeMarker(event.latLng);
            });
            var latlng = google.maps.event.addDomListener(map, 'click', function (event) {
                var lat = event.latLng.lat();
                var lng = event.latLng.lng();
                var latlng = [lat, lng];
                document.getElementById("latitude").value = lat;
                document.getElementById("longitude").value = lng;
                //alert("Latitude: " + event.latLng.lat() + " " + ", longitude: " + event.latLng.lng());
                return latlng;
                @*@Html.HiddenFor(m => m.CurrentVenue.Latitude, new { id = "Latitude", @value = latlng })*@

                // need to fix this

            });
                        
        }
        window.onload = function () { initialize() };
    </script>
    <style>
        div#gmap {
            width: 40%;
            height: 500px;
            border: double;
        }
    </style>
</head>

<body>
    <form id="form1" runat="server">
        <center>
            <!-- MAP HOLDER -->
            <div id="gmap"></div>


        </center>

    </form>
</body>

</html>
}

EventPlanner/Views/Promoter/Delete.cshtml
@model EventPlanner.Models.Entertainment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entertainment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Event.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restriction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restriction)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EventPlanner/Views/Promoter/Events.cshtml

@{
    ViewBag.Title = "Events";
}

<h2>Events</h2>

<p>
    @Html.ActionLink("Create New Event", "CreateEvent")
</p>


EventPlanner/Views/Promoter/Index.cshtml
@model IEnumerable<EventPlanner.Models.Entertainment>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("My Info", "MyInfo", "Promoter")
</p>
<p>
    @Html.ActionLink("Events", "Index", "Events")
</p>
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Event.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Venue.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restriction)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Event.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Venue.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restriction)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@

EventPlanner/Views/Promoter/MyInfo.cshtml

@{
    ViewBag.Title = "MyInfo";
}




EventPlanner/Views/Promoter/ViewVenues.cshtml
@model EventPlanner.Models.ViewVenuesViewModel
@{
    ViewBag.Title = "ViewVenues";
}
<head>
    <style>
        h3{
            text-indent: 50px;
        }
        p {
            text-indent: 100px;
        }
    </style>
</head>

<h2>Your Venues</h2>

<table class="table" style="color:#ffffff;">
    @foreach (var venue in Model.UserVenues)
    {
        <tr>
            <th>
                <h2> @venue.Name: </h2>
                <h3>Shows: </h3>
                @foreach (var entertainment in Model.UserEntertainment)
                {
                    if (entertainment.VenueId == venue.Id)
                    {
                        <p> - @entertainment.Name</p>
                    }
                }
            </th>
        </tr>
    }
    @Html.ActionLink("Back to List", "Index")
</table>